name: Update Exchange Rates

on:
  repository_dispatch:
    types: [update-exchange-rates]

jobs:
  update_data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions@github.com"

      - name: Decode Base64 content and update data.json
        run: |
          # Decode the Base64 content and save it to backend/data.json
          echo "${{ github.event.client_payload.base64_content }}" | base64 --decode > backend/data.json

      - name: Commit changes
        run: |
          git add backend/data.json
          git commit -m "${{ github.event.client_payload.message }}"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.DB_TOKEN }}
