name: Update Exchange Rates

on:
  repository_dispatch:
    types: [update_exchange_rates]

jobs:
  update-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update data.json
        run: |
          echo "${{ github.event.client_payload.data }}" > backend/data.json

      - name: Commit changes
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git add backend/data.json
          git commit -m "Updated exchange rates"

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
