name: Update Currency Exchange Rates

on:
  workflow_dispatch:
    inputs:
      aba_buy:
        description: 'ABA Buy Rate'
        required: true
        default: '4000'
      aba_sell:
        description: 'ABA Sell Rate'
        required: true
        default: '4100'
      ace_buy:
        description: 'ACELEDA Buy Rate'
        required: true
        default: '4100'
      ace_sell:
        description: 'ACELEDA Sell Rate'
        required: true
        default: '4200'
      wing_buy:
        description: 'WING Buy Rate'
        required: true
        default: '4200'
      wing_sell:
        description: 'WING Sell Rate'
        required: true
        default: '4300'

jobs:
  update_rates:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git configuration
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions@github.com"

      - name: Update data.json with new exchange rates
        run: |
          echo '{
            "banks": [
              {"name": "ABA", "buy": "${{ github.event.inputs.aba_buy }}", "sell": "${{ github.event.inputs.aba_sell }}"},
              {"name": "ACELEDA", "buy": "${{ github.event.inputs.ace_buy }}", "sell": "${{ github.event.inputs.ace_sell }}"},
              {"name": "WING", "buy": "${{ github.event.inputs.wing_buy }}", "sell": "${{ github.event.inputs.wing_sell }}"}
            ]
          }' > backend/data.json

      - name: Commit and push changes
        run: |
          git add backend/data.json
          git commit -m "Update exchange rates"
          git push
        env:
          DB_TOKEN: ${{ secrets.DB_TOKEN }}  # Use the GitHub secret token here
