name: Update Data JSON

on:
  push:
    branches:
      - main
jobs:
  update-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Update data.json file
        run: |
          # Add script here to update data.json (or use any commands)
          echo '{"USD": "4000", "KHR": "1650"}' > data.json
      - name: Commit and push updated data.json
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add data.json
          git commit -m "Updated exchange rates"
          git push
